In [1]:
import pandas as pd
#!pip install forex_python
from forex_python.converter import CurrencyRates

In [2]:
boat_data = "boat_data.csv"

# Read the boat data
boat_df = pd.read_csv(boat_data)

# Display the data table for preview
boat_df.head(5)

,Price,Boat Type,Manufacturer,Type,Year Built,Length,Width,Material,Location,Number of views last 7 days
0,CHF 3337,Motor Yacht,Rigiflex power boats,new boat from stock,2017,4.00,1.90,NaN,Switzerland Â» Lake Geneva Â» VÃ©senaz,226
1,EUR 3490,Center console boat,Terhi power boats,new boat from stock,2020,4.00,1.50,Thermoplastic,Germany Â» BÃ¶nningstedt,75
2,CHF 3770,Sport Boat,Marine power boats,new boat from stock,0,3.69,1.42,Aluminium,Switzerland Â» Lake of Zurich Â» StÃ¤fa ZH,124
3,DKK 25900,Sport Boat,Pioner power boats,new boat from stock,2020,3.00,1.00,NaN,Denmark Â» Svendborg,64
4,EUR 3399,Fishing Boat,Linder power boats,new boat from stock,2019,3.55,1.46,Aluminium,Germany Â» Bayern Â» MÃ¼nchen,58

In [3]:
data_df = boat_df[['Price', 'Boat Type', 'Manufacturer', 'Type', 'Year Built', 'Length', 'Width', 'Material', 
                                        'Location', 'Number of views last 7 days']]
data_df

,Price,Boat Type,Manufacturer,Type,Year Built,Length,Width,Material,Location,Number of views last 7 days
0,CHF 3337,Motor Yacht,Rigiflex power boats,new boat from stock,2017,4.00,1.90,NaN,Switzerland Â» Lake Geneva Â» VÃ©senaz,226
1,EUR 3490,Center console boat,Terhi power boats,new boat from stock,2020,4.00,1.50,Thermoplastic,Germany Â» BÃ¶nningstedt,75
2,CHF 3770,Sport Boat,Marine power boats,new boat from stock,0,3.69,1.42,Aluminium,Switzerland Â» Lake of Zurich Â» StÃ¤fa ZH,124
3,DKK 25900,Sport Boat,Pioner power boats,new boat from stock,2020,3.00,1.00,NaN,Denmark Â» Svendborg,64
4,EUR 3399,Fishing Boat,Linder power boats,new boat from stock,2019,3.55,1.46,Aluminium,Germany Â» Bayern Â» MÃ¼nchen,58
...,...,...,...,...,...,...,...,...,...,...
9883,CHF 4900,Sport Boat,Sea Ray power boats,"Used boat,Unleaded",1987,6.30,2.44,NaN,Switzerland Â» Lago Maggiore Â» Riazzino,1116
9884,EUR 4516,Sport Boat,NaN,new boat from stock,0,4.17,1.68,GRP,Germany Â» Hamburg Â» HAMBURG,94
9885,EUR 4499,Sport Boat,BlueCraft power boats,"new boat from stock,Unleaded",2020,4.40,1.80,GRP,Germany Â» Nordrhein-Westfalen Â» Wesel,354
9886,EUR 4300,Pontoon Boat,Whaly power boats,new boat from stock,2018,4.37,1.89,NaN,Italy Â» Dormelletto,266
9887,CHF 3780,Fishing Boat,DarekCo power boats,new boat from stock,2019,3.60,1.60,GRP,Switzerland Â» Brienzersee Â» Brienz,194

In [4]:
#Create column header for Currency from Price column
data_df['Currency'] = data_df['Price'].str[:3]
data_df.head()

,Price,Boat Type,Manufacturer,Type,Year Built,Length,Width,Material,Location,Number of views last 7 days,Currency
0,CHF 3337,Motor Yacht,Rigiflex power boats,new boat from stock,2017,4.00,1.90,NaN,Switzerland Â» Lake Geneva Â» VÃ©senaz,226,CHF
1,EUR 3490,Center console boat,Terhi power boats,new boat from stock,2020,4.00,1.50,Thermoplastic,Germany Â» BÃ¶nningstedt,75,EUR
2,CHF 3770,Sport Boat,Marine power boats,new boat from stock,0,3.69,1.42,Aluminium,Switzerland Â» Lake of Zurich Â» StÃ¤fa ZH,124,CHF
3,DKK 25900,Sport Boat,Pioner power boats,new boat from stock,2020,3.00,1.00,NaN,Denmark Â» Svendborg,64,DKK
4,EUR 3399,Fishing Boat,Linder power boats,new boat from stock,2019,3.55,1.46,Aluminium,Germany Â» Bayern Â» MÃ¼nchen,58,EUR

In [5]:
#Remove Currency prefix from Price column
data_df['Price'] = data_df['Price'].str.slice(3)
data_df.head()

,Price,Boat Type,Manufacturer,Type,Year Built,Length,Width,Material,Location,Number of views last 7 days,Currency
0,3337,Motor Yacht,Rigiflex power boats,new boat from stock,2017,4.00,1.90,NaN,Switzerland Â» Lake Geneva Â» VÃ©senaz,226,CHF
1,3490,Center console boat,Terhi power boats,new boat from stock,2020,4.00,1.50,Thermoplastic,Germany Â» BÃ¶nningstedt,75,EUR
2,3770,Sport Boat,Marine power boats,new boat from stock,0,3.69,1.42,Aluminium,Switzerland Â» Lake of Zurich Â» StÃ¤fa ZH,124,CHF
3,25900,Sport Boat,Pioner power boats,new boat from stock,2020,3.00,1.00,NaN,Denmark Â» Svendborg,64,DKK
4,3399,Fishing Boat,Linder power boats,new boat from stock,2019,3.55,1.46,Aluminium,Germany Â» Bayern Â» MÃ¼nchen,58,EUR

In [6]:
#Reorder the dataframe so that Currency is listed first
reorder_df = data_df[['Currency', 'Price', 'Boat Type', 'Manufacturer','Type','Year Built','Length','Width','Material',
                      'Location','Number of views last 7 days']]
reorder_df.head()

,Currency,Price,Boat Type,Manufacturer,Type,Year Built,Length,Width,Material,Location,Number of views last 7 days
0,CHF,3337,Motor Yacht,Rigiflex power boats,new boat from stock,2017,4.00,1.90,NaN,Switzerland Â» Lake Geneva Â» VÃ©senaz,226
1,EUR,3490,Center console boat,Terhi power boats,new boat from stock,2020,4.00,1.50,Thermoplastic,Germany Â» BÃ¶nningstedt,75
2,CHF,3770,Sport Boat,Marine power boats,new boat from stock,0,3.69,1.42,Aluminium,Switzerland Â» Lake of Zurich Â» StÃ¤fa ZH,124
3,DKK,25900,Sport Boat,Pioner power boats,new boat from stock,2020,3.00,1.00,NaN,Denmark Â» Svendborg,64
4,EUR,3399,Fishing Boat,Linder power boats,new boat from stock,2019,3.55,1.46,Aluminium,Germany Â» Bayern Â» MÃ¼nchen,58

In [7]:
#Check the currencies listed.
#Note that Â£ might be considered GBP 
reorder_df['Currency'].value_counts()

EUR    8430
CHF     980
Â£      298
DKK     180
Name: Currency, dtype: int64

In [8]:
#reorder_df['date_time'] = pd.to_datetime('now')
#reorder_df.head()

In [9]:
#reorder_df.drop(['date_time'])
#reorder_df.head()

In [10]:
reorder_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9888 entries, 0 to 9887
Data columns (total 11 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Currency                     9888 non-null   object
 1   Price                        9888 non-null   object
 2   Boat Type                    9888 non-null   object
 3   Manufacturer                 8550 non-null   object
 4   Type                         9882 non-null   object
 5   Year Built                   9888 non-null   int64
 6   Length                       9879 non-null   float64
 7   Width                        9832 non-null   float64
 8   Material                     8139 non-null   object
 9   Location                     9852 non-null   object
 10  Number of views last 7 days  9888 non-null   int64
dtypes: float64(2), int64(2), object(7)
memory usage: 849.9+ KB

In [11]:
reorder_df.Price = reorder_df.Price.astype(float)
(print(reorder_df.dtypes))

Currency                        object
Price                          float64
Boat Type                       object
Manufacturer                    object
Type                            object
Year Built                       int64
Length                         float64
Width                          float64
Material                        object
Location                        object
Number of views last 7 days      int64
dtype: object

In [12]:
#Use a date to reference the currency conversation rate
reorder_df['date'] = pd.Timestamp('2023-09-05')
reorder_df.head()

,Currency,Price,Boat Type,Manufacturer,Type,Year Built,Length,Width,Material,Location,Number of views last 7 days,date
0,CHF,3337.0,Motor Yacht,Rigiflex power boats,new boat from stock,2017,4.00,1.90,NaN,Switzerland Â» Lake Geneva Â» VÃ©senaz,226,2023-09-05
1,EUR,3490.0,Center console boat,Terhi power boats,new boat from stock,2020,4.00,1.50,Thermoplastic,Germany Â» BÃ¶nningstedt,75,2023-09-05
2,CHF,3770.0,Sport Boat,Marine power boats,new boat from stock,0,3.69,1.42,Aluminium,Switzerland Â» Lake of Zurich Â» StÃ¤fa ZH,124,2023-09-05
3,DKK,25900.0,Sport Boat,Pioner power boats,new boat from stock,2020,3.00,1.00,NaN,Denmark Â» Svendborg,64,2023-09-05
4,EUR,3399.0,Fishing Boat,Linder power boats,new boat from stock,2019,3.55,1.46,Aluminium,Germany Â» Bayern Â» MÃ¼nchen,58,2023-09-05

In [13]:
#Currency conversion dataframe
cc = pd.DataFrame(
    {'from':['EUR','CHF','EUR','DKK','EUR','Â£'],'to':['CHF','EUR','DKK','EUR','Â£','EUR'],'rate':[.95,1.05,7.45,.13,1.00,1.00]},
    

)
cc

  from   to  rate
0  EUR  CHF  0.95
1  CHF  EUR  1.05
2  EUR  DKK  7.45
3  DKK  EUR  0.13
4  EUR   Â£  1.00
5   Â£  EUR  1.00

In [14]:
#Applying conversion to EUR:
reorder_df['price in EUR'] = reorder_df['Price']*reorder_df.merge(cc[cc.to=='EUR'].append({'from':'EUR','to':'EUR','rate':1},ignore_index=True),left_on='Currency',right_on='from',how='left')['rate']
reorder_df

C:\Users\justi\AppData\Local\Temp\ipykernel_24328\3231562371.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  reorder_df['price in EUR'] = reorder_df['Price']*reorder_df.merge(cc[cc.to=='EUR'].append({'from':'EUR','to':'EUR','rate':1},ignore_index=True),left_on='Currency',right_on='from',how='left')['rate']

,Currency,Price,Boat Type,Manufacturer,Type,Year Built,Length,Width,Material,Location,Number of views last 7 days,date,price in EUR
0,CHF,3337.0,Motor Yacht,Rigiflex power boats,new boat from stock,2017,4.00,1.90,NaN,Switzerland Â» Lake Geneva Â» VÃ©senaz,226,2023-09-05,3503.85
1,EUR,3490.0,Center console boat,Terhi power boats,new boat from stock,2020,4.00,1.50,Thermoplastic,Germany Â» BÃ¶nningstedt,75,2023-09-05,3490.00
2,CHF,3770.0,Sport Boat,Marine power boats,new boat from stock,0,3.69,1.42,Aluminium,Switzerland Â» Lake of Zurich Â» StÃ¤fa ZH,124,2023-09-05,3958.50
3,DKK,25900.0,Sport Boat,Pioner power boats,new boat from stock,2020,3.00,1.00,NaN,Denmark Â» Svendborg,64,2023-09-05,3367.00
4,EUR,3399.0,Fishing Boat,Linder power boats,new boat from stock,2019,3.55,1.46,Aluminium,Germany Â» Bayern Â» MÃ¼nchen,58,2023-09-05,3399.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9883,CHF,4900.0,Sport Boat,Sea Ray power boats,"Used boat,Unleaded",1987,6.30,2.44,NaN,Switzerland Â» Lago Maggiore Â» Riazzino,1116,2023-09-05,5145.00
9884,EUR,4516.0,Sport Boat,NaN,new boat from stock,0,4.17,1.68,GRP,Germany Â» Hamburg Â» HAMBURG,94,2023-09-05,4516.00
9885,EUR,4499.0,Sport Boat,BlueCraft power boats,"new boat from stock,Unleaded",2020,4.40,1.80,GRP,Germany Â» Nordrhein-Westfalen Â» Wesel,354,2023-09-05,4499.00
9886,EUR,4300.0,Pontoon Boat,Whaly power boats,new boat from stock,2018,4.37,1.89,NaN,Italy Â» Dormelletto,266,2023-09-05,4300.00
9887,CHF,3780.0,Fishing Boat,DarekCo power boats,new boat from stock,2019,3.60,1.60,GRP,Switzerland Â» Brienzersee Â» Brienz,194,2023-09-05,3969.00

In [15]:
#Applying conversion to USD:
reorder_df['price in USD'] = round(reorder_df['price in EUR']*1.07,2)
reorder_df.head()

,Currency,Price,Boat Type,Manufacturer,Type,Year Built,Length,Width,Material,Location,Number of views last 7 days,date,price in EUR,price in USD
0,CHF,3337.0,Motor Yacht,Rigiflex power boats,new boat from stock,2017,4.00,1.90,NaN,Switzerland Â» Lake Geneva Â» VÃ©senaz,226,2023-09-05,3503.85,3749.12
1,EUR,3490.0,Center console boat,Terhi power boats,new boat from stock,2020,4.00,1.50,Thermoplastic,Germany Â» BÃ¶nningstedt,75,2023-09-05,3490.00,3734.30
2,CHF,3770.0,Sport Boat,Marine power boats,new boat from stock,0,3.69,1.42,Aluminium,Switzerland Â» Lake of Zurich Â» StÃ¤fa ZH,124,2023-09-05,3958.50,4235.60
3,DKK,25900.0,Sport Boat,Pioner power boats,new boat from stock,2020,3.00,1.00,NaN,Denmark Â» Svendborg,64,2023-09-05,3367.00,3602.69
4,EUR,3399.0,Fishing Boat,Linder power boats,new boat from stock,2019,3.55,1.46,Aluminium,Germany Â» Bayern Â» MÃ¼nchen,58,2023-09-05,3399.00,3636.93

In [16]:
#In general, to remove non-ascii characters, use str.encode with errors='ignore':
#Source: https://www.appsloveworld.com/pandas/100/21/remove-non-ascii-characters-from-string-columns-in-pandas#google_vignette

#reorder_df['Location'] = reorder_df['Location'].str.encode('ascii', 'ignore').str.decode('utf-8')
#reorder_df.head()

In [17]:
# Input string with ASCII characters
#ascii_text = "Hello, GermanyÂ»!"
# Convert ASCII to Unicode (standard characters)
#unicode_text = ascii_text.encode('cp1252').decode('utf-8')
# Print the result
#print(unicode_text)

In [18]:
#original_string = "Germany Â» Bayern Â» MÃ¼nchen"
#decoded_string = original_string.encode('latin-1').decode('utf-8')
# Print the decoded string
#print(decoded_string)

In [19]:
reorder_df['Location'] = reorder_df['Location'].str.encode('latin-1').str.decode('utf-8')
reorder_df.head()

,Currency,Price,Boat Type,Manufacturer,Type,Year Built,Length,Width,Material,Location,Number of views last 7 days,date,price in EUR,price in USD
0,CHF,3337.0,Motor Yacht,Rigiflex power boats,new boat from stock,2017,4.00,1.90,NaN,Switzerland » Lake Geneva » Vésenaz,226,2023-09-05,3503.85,3749.12
1,EUR,3490.0,Center console boat,Terhi power boats,new boat from stock,2020,4.00,1.50,Thermoplastic,Germany » Bönningstedt,75,2023-09-05,3490.00,3734.30
2,CHF,3770.0,Sport Boat,Marine power boats,new boat from stock,0,3.69,1.42,Aluminium,Switzerland » Lake of Zurich » Stäfa ZH,124,2023-09-05,3958.50,4235.60
3,DKK,25900.0,Sport Boat,Pioner power boats,new boat from stock,2020,3.00,1.00,NaN,Denmark » Svendborg,64,2023-09-05,3367.00,3602.69
4,EUR,3399.0,Fishing Boat,Linder power boats,new boat from stock,2019,3.55,1.46,Aluminium,Germany » Bayern » München,58,2023-09-05,3399.00,3636.93

In [20]:
reorder_df['Manufacturer'] = reorder_df['Manufacturer'].str.encode('latin-1').str.decode('utf-8')
reorder_df

,Currency,Price,Boat Type,Manufacturer,Type,Year Built,Length,Width,Material,Location,Number of views last 7 days,date,price in EUR,price in USD
0,CHF,3337.0,Motor Yacht,Rigiflex power boats,new boat from stock,2017,4.00,1.90,NaN,Switzerland » Lake Geneva » Vésenaz,226,2023-09-05,3503.85,3749.12
1,EUR,3490.0,Center console boat,Terhi power boats,new boat from stock,2020,4.00,1.50,Thermoplastic,Germany » Bönningstedt,75,2023-09-05,3490.00,3734.30
2,CHF,3770.0,Sport Boat,Marine power boats,new boat from stock,0,3.69,1.42,Aluminium,Switzerland » Lake of Zurich » Stäfa ZH,124,2023-09-05,3958.50,4235.60
3,DKK,25900.0,Sport Boat,Pioner power boats,new boat from stock,2020,3.00,1.00,NaN,Denmark » Svendborg,64,2023-09-05,3367.00,3602.69
4,EUR,3399.0,Fishing Boat,Linder power boats,new boat from stock,2019,3.55,1.46,Aluminium,Germany » Bayern » München,58,2023-09-05,3399.00,3636.93
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9883,CHF,4900.0,Sport Boat,Sea Ray power boats,"Used boat,Unleaded",1987,6.30,2.44,NaN,Switzerland » Lago Maggiore » Riazzino,1116,2023-09-05,5145.00,5505.15
9884,EUR,4516.0,Sport Boat,NaN,new boat from stock,0,4.17,1.68,GRP,Germany » Hamburg » HAMBURG,94,2023-09-05,4516.00,4832.12
9885,EUR,4499.0,Sport Boat,BlueCraft power boats,"new boat from stock,Unleaded",2020,4.40,1.80,GRP,Germany » Nordrhein-Westfalen » Wesel,354,2023-09-05,4499.00,4813.93
9886,EUR,4300.0,Pontoon Boat,Whaly power boats,new boat from stock,2018,4.37,1.89,NaN,Italy » Dormelletto,266,2023-09-05,4300.00,4601.00
9887,CHF,3780.0,Fishing Boat,DarekCo power boats,new boat from stock,2019,3.60,1.60,GRP,Switzerland » Brienzersee » Brienz,194,2023-09-05,3969.00,4246.83

In [24]:
reorder_df['Manufacturer'].value_counts()

Bénéteau power boats           631
Jeanneau power boats           537
Sunseeker power boats          383
Princess power boats           241
Sea Ray power boats            239
                              ...
Aegean Yachts power boats        1
ISA Yachts power boats           1
Couach power boats               1
Perini Navi Spa power boats      1
Hunter power boats               1
Name: Manufacturer, Length: 910, dtype: int64

In [21]:
reorder_df['Location'] = reorder_df['Location'].str.replace('»',',')
reorder_df.head()

,Currency,Price,Boat Type,Manufacturer,Type,Year Built,Length,Width,Material,Location,Number of views last 7 days,date,price in EUR,price in USD
0,CHF,3337.0,Motor Yacht,Rigiflex power boats,new boat from stock,2017,4.00,1.90,NaN,"Switzerland , Lake Geneva , Vésenaz",226,2023-09-05,3503.85,3749.12
1,EUR,3490.0,Center console boat,Terhi power boats,new boat from stock,2020,4.00,1.50,Thermoplastic,"Germany , Bönningstedt",75,2023-09-05,3490.00,3734.30
2,CHF,3770.0,Sport Boat,Marine power boats,new boat from stock,0,3.69,1.42,Aluminium,"Switzerland , Lake of Zurich , Stäfa ZH",124,2023-09-05,3958.50,4235.60
3,DKK,25900.0,Sport Boat,Pioner power boats,new boat from stock,2020,3.00,1.00,NaN,"Denmark , Svendborg",64,2023-09-05,3367.00,3602.69
4,EUR,3399.0,Fishing Boat,Linder power boats,new boat from stock,2019,3.55,1.46,Aluminium,"Germany , Bayern , München",58,2023-09-05,3399.00,3636.93

In [22]:
columnsplit = reorder_df['Location'].str.split(" , ", expand=True)
final_df = reorder_df.assign(Country=columnsplit[0],City=columnsplit[1])
final_df.head()

,Currency,Price,Boat Type,Manufacturer,Type,Year Built,Length,Width,Material,Location,Number of views last 7 days,date,price in EUR,price in USD,Country,City
0,CHF,3337.0,Motor Yacht,Rigiflex power boats,new boat from stock,2017,4.00,1.90,NaN,"Switzerland , Lake Geneva , Vésenaz",226,2023-09-05,3503.85,3749.12,Switzerland,Lake Geneva
1,EUR,3490.0,Center console boat,Terhi power boats,new boat from stock,2020,4.00,1.50,Thermoplastic,"Germany , Bönningstedt",75,2023-09-05,3490.00,3734.30,Germany,Bönningstedt
2,CHF,3770.0,Sport Boat,Marine power boats,new boat from stock,0,3.69,1.42,Aluminium,"Switzerland , Lake of Zurich , Stäfa ZH",124,2023-09-05,3958.50,4235.60,Switzerland,Lake of Zurich
3,DKK,25900.0,Sport Boat,Pioner power boats,new boat from stock,2020,3.00,1.00,NaN,"Denmark , Svendborg",64,2023-09-05,3367.00,3602.69,Denmark,Svendborg
4,EUR,3399.0,Fishing Boat,Linder power boats,new boat from stock,2019,3.55,1.46,Aluminium,"Germany , Bayern , München",58,2023-09-05,3399.00,3636.93,Germany,Bayern

In [26]:
typesplit = final_df['Type'].str.split(",", expand=True)
final_df_1 = final_df.assign(Condition=typesplit[0],Fuel=typesplit[1])
final_df_1.head()

,Currency,Price,Boat Type,Manufacturer,Type,Year Built,Length,Width,Material,Location,Number of views last 7 days,date,price in EUR,price in USD,Country,City,Condition,Fuel
0,CHF,3337.0,Motor Yacht,Rigiflex power boats,new boat from stock,2017,4.00,1.90,NaN,"Switzerland , Lake Geneva , Vésenaz",226,2023-09-05,3503.85,3749.12,Switzerland,Lake Geneva,new boat from stock,None
1,EUR,3490.0,Center console boat,Terhi power boats,new boat from stock,2020,4.00,1.50,Thermoplastic,"Germany , Bönningstedt",75,2023-09-05,3490.00,3734.30,Germany,Bönningstedt,new boat from stock,None
2,CHF,3770.0,Sport Boat,Marine power boats,new boat from stock,0,3.69,1.42,Aluminium,"Switzerland , Lake of Zurich , Stäfa ZH",124,2023-09-05,3958.50,4235.60,Switzerland,Lake of Zurich,new boat from stock,None
3,DKK,25900.0,Sport Boat,Pioner power boats,new boat from stock,2020,3.00,1.00,NaN,"Denmark , Svendborg",64,2023-09-05,3367.00,3602.69,Denmark,Svendborg,new boat from stock,None
4,EUR,3399.0,Fishing Boat,Linder power boats,new boat from stock,2019,3.55,1.46,Aluminium,"Germany , Bayern , München",58,2023-09-05,3399.00,3636.93,Germany,Bayern,new boat from stock,None

In [27]:
final_df_1 = final_df_1.drop(['Type','Location'], axis=1)
final_df_1.head()

,Currency,Price,Boat Type,Manufacturer,Year Built,Length,Width,Material,Number of views last 7 days,date,price in EUR,price in USD,Country,City,Condition,Fuel
0,CHF,3337.0,Motor Yacht,Rigiflex power boats,2017,4.00,1.90,NaN,226,2023-09-05,3503.85,3749.12,Switzerland,Lake Geneva,new boat from stock,None
1,EUR,3490.0,Center console boat,Terhi power boats,2020,4.00,1.50,Thermoplastic,75,2023-09-05,3490.00,3734.30,Germany,Bönningstedt,new boat from stock,None
2,CHF,3770.0,Sport Boat,Marine power boats,0,3.69,1.42,Aluminium,124,2023-09-05,3958.50,4235.60,Switzerland,Lake of Zurich,new boat from stock,None
3,DKK,25900.0,Sport Boat,Pioner power boats,2020,3.00,1.00,NaN,64,2023-09-05,3367.00,3602.69,Denmark,Svendborg,new boat from stock,None
4,EUR,3399.0,Fishing Boat,Linder power boats,2019,3.55,1.46,Aluminium,58,2023-09-05,3399.00,3636.93,Germany,Bayern,new boat from stock,None

In [28]:
final_df_1.columns.values

array(['Currency', 'Price', 'Boat Type', 'Manufacturer', 'Year Built',
       'Length', 'Width', 'Material', 'Number of views last 7 days',
       'date', 'price in EUR', 'price in USD', 'Country', 'City',
       'Condition', 'Fuel'], dtype=object)

In [30]:
ETL_Final = final_df_1[['Currency', 'Price', 'Boat Type', 'Manufacturer', 'Year Built',
       'Length', 'Width', 'Material', 'Number of views last 7 days',
       'date', 'price in EUR', 'price in USD', 'City','Country',
       'Condition', 'Fuel']]
ETL_Final.head()

,Currency,Price,Boat Type,Manufacturer,Year Built,Length,Width,Material,Number of views last 7 days,date,price in EUR,price in USD,City,Country,Condition,Fuel
0,CHF,3337.0,Motor Yacht,Rigiflex power boats,2017,4.00,1.90,NaN,226,2023-09-05,3503.85,3749.12,Lake Geneva,Switzerland,new boat from stock,None
1,EUR,3490.0,Center console boat,Terhi power boats,2020,4.00,1.50,Thermoplastic,75,2023-09-05,3490.00,3734.30,Bönningstedt,Germany,new boat from stock,None
2,CHF,3770.0,Sport Boat,Marine power boats,0,3.69,1.42,Aluminium,124,2023-09-05,3958.50,4235.60,Lake of Zurich,Switzerland,new boat from stock,None
3,DKK,25900.0,Sport Boat,Pioner power boats,2020,3.00,1.00,NaN,64,2023-09-05,3367.00,3602.69,Svendborg,Denmark,new boat from stock,None
4,EUR,3399.0,Fishing Boat,Linder power boats,2019,3.55,1.46,Aluminium,58,2023-09-05,3399.00,3636.93,Bayern,Germany,new boat from stock,None

In [31]:
ETL_Final = ETL_Final.rename(columns={'date': 'Date', 'price in EUR': 'Price in EUR', 'price in USD': 'Price in USD',
                                      'Length': 'Length (meters)','Width': 'Width (meters)'})
ETL_Final

,Currency,Price,Boat Type,Manufacturer,Year Built,Length (meters),Width (meters),Material,Number of views last 7 days,Date,Price in EUR,Price in USD,City,Country,Condition,Fuel
0,CHF,3337.0,Motor Yacht,Rigiflex power boats,2017,4.00,1.90,NaN,226,2023-09-05,3503.85,3749.12,Lake Geneva,Switzerland,new boat from stock,None
1,EUR,3490.0,Center console boat,Terhi power boats,2020,4.00,1.50,Thermoplastic,75,2023-09-05,3490.00,3734.30,Bönningstedt,Germany,new boat from stock,None
2,CHF,3770.0,Sport Boat,Marine power boats,0,3.69,1.42,Aluminium,124,2023-09-05,3958.50,4235.60,Lake of Zurich,Switzerland,new boat from stock,None
3,DKK,25900.0,Sport Boat,Pioner power boats,2020,3.00,1.00,NaN,64,2023-09-05,3367.00,3602.69,Svendborg,Denmark,new boat from stock,None
4,EUR,3399.0,Fishing Boat,Linder power boats,2019,3.55,1.46,Aluminium,58,2023-09-05,3399.00,3636.93,Bayern,Germany,new boat from stock,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9883,CHF,4900.0,Sport Boat,Sea Ray power boats,1987,6.30,2.44,NaN,1116,2023-09-05,5145.00,5505.15,Lago Maggiore,Switzerland,Used boat,Unleaded
9884,EUR,4516.0,Sport Boat,NaN,0,4.17,1.68,GRP,94,2023-09-05,4516.00,4832.12,Hamburg,Germany,new boat from stock,None
9885,EUR,4499.0,Sport Boat,BlueCraft power boats,2020,4.40,1.80,GRP,354,2023-09-05,4499.00,4813.93,Nordrhein-Westfalen,Germany,new boat from stock,Unleaded
9886,EUR,4300.0,Pontoon Boat,Whaly power boats,2018,4.37,1.89,NaN,266,2023-09-05,4300.00,4601.00,Dormelletto,Italy,new boat from stock,None
9887,CHF,3780.0,Fishing Boat,DarekCo power boats,2019,3.60,1.60,GRP,194,2023-09-05,3969.00,4246.83,Brienzersee,Switzerland,new boat from stock,None

In [34]:
manu_count = len(pd.unique(ETL_Final['Manufacturer']))
manu_count

911

In [37]:
print(ETL_Final.dtypes)

Currency                               object
Price                                 float64
Boat Type                              object
Manufacturer                           object
Year Built                              int64
Length (meters)                       float64
Width (meters)                        float64
Material                               object
Number of views last 7 days             int64
Date                           datetime64[ns]
Price in EUR                          float64
Price in USD                          float64
City                                   object
Country                                object
Condition                              object
Fuel                                   object
dtype: object

In [35]:
ETL_Final.to_csv('ETL_Final.csv')